---

- name: Download GeoIP data file
  get_url:
    url: "{{ matomo_geoip_data_url }}"
    dest: "{{ matomo_path.temporary }}"

- name: Decompress the GeoIP data file
  # Necessary until https://github.com/ansible/ansible/pull/23048 gets merged.
  command: gunzip {{ matomo_geoip_data_compressed }}
  args:
    chdir: "{{ matomo_path.temporary }}"
    creates: "{{ matomo_path.temporary }}/{{ matomo_geoip_data_filename }}"

- name: Copy GeoIP data file into page for Matomo's use
  copy:
    remote_src: yes
    src: "{{ matomo_path.temporary }}/{{ matomo_geoip_data_filename }}"
    dest: "{{ matomo_path.docroot }}/misc/DBIP-City.mmdb"
  become: true
