---
# Web server configurator

- name: Inject the Matomo site's Nginx configuration
  template:
    src: "matomo.conf.j2"
    dest: "{{ matomo_web_config_dir['available'] }}/matomo.conf"
    owner: "root"
    group: "root"
    mode: "preserve"
    force: no

- name: Enable the site
  file:
    src: "{{ matomo_web_config_file['regular'] }}"
    dest: "{{ matomo_web_config_file['link'] }}"
    state: link
  notify: "(Handler: All OSs) Reload NGINX"
