---
# Database creator

- name: Create Matomo's MySQL database
  mysql_db:
    name: "{{ matomo_db['name'] }}"
    state: present
  register: matomo_db['exists']

- name: Create Matomo's database user
  mysql_user:
    name: "{{ matomo_db['user'] }}"
    password: "{{ matomo_db['password'] }}"
    state: present
    priv: "{{ matomo_db['name'] }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE\ TEMPORARY\ TABLES,LOCK\ TABLES"
