---
# HTTPS certificate getter

- name: Run a separate role to install the HTTPS certificate
  import_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ matomo_https_certificate_admin_email }}"
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
          - "{{ matomo_domain }}"
  when: matomo_protocol == "https"
