---
# HTTPS certificate getter

- name: Run a separate role to install the HTTPS certificate
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: "{{ matomo_https_certificate_admin_email }}"
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - domains:
          - "{{ matomo_domain }}"
    # The Debian package already provides a cron job.
    certbot_auto_renew: false
    # This is necessary until https://github.com/geerlingguy/ansible-role-certbot/issues/105 gets fixed.
    ansible_become: yes
  when: matomo_protocol == "https"
