---
# Debian package installer

# Originally from https://mackuba.eu/2019/02/02/setting-up-piwik/

#TODO Try to get HTTPS working?
- name: "Load the Matomo apt repository key"
  apt_key:
    id: 1FD752571FE36FF23F78F91B81E2E78B66FED89E
    url: http://debian.matomo.org/repository.gpg

- name: "Add the Matomo repository to apt"
  apt_repository: repo="deb https://debian.matomo.org/ piwik main"

- name: "Enable automatic upgrades in debconf"
  debconf:
    name: matomo
    question: matomo/automatic-upgrade
    value: true
    vtype: boolean

- name: "Install Matomo apt package"
  apt:
    name: matomo
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
